source 'https://anonymous:devcloud@mirrors.huaweicloud.com/repository/rubygems/'

gem 'jwt'
gem 'sinatra'
gem 'puma'
gem 'haml'
gem 'sequel'
gem 'sequel_secure_password'
gem 'sinatra-sequel'
gem 'sqlite3'
gem 'multi_json'
gem 'sprockets'
