package com.kcoin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setLogin(java.lang.String login) {
		set("login", login);
		return (M)this;
	}
	
	public java.lang.String getLogin() {
		return getStr("login");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setOauthProvider(java.lang.String oauthProvider) {
		set("oauth_provider", oauthProvider);
		return (M)this;
	}
	
	public java.lang.String getOauthProvider() {
		return getStr("oauth_provider");
	}

	public M setOpenId(java.lang.String openId) {
		set("open_id", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("open_id");
	}

	public M setPasswordDigest(java.lang.String passwordDigest) {
		set("password_digest", passwordDigest);
		return (M)this;
	}
	
	public java.lang.String getPasswordDigest() {
		return getStr("password_digest");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setAvatarUrl(java.lang.String avatarUrl) {
		set("avatar_url", avatarUrl);
		return (M)this;
	}
	
	public java.lang.String getAvatarUrl() {
		return getStr("avatar_url");
	}

	public M setCreatedAt(java.lang.String createdAt) {
		set("created_at", createdAt);
		return (M)this;
	}
	
	public java.lang.String getCreatedAt() {
		return getStr("created_at");
	}

	public M setUpdatedAt(java.lang.String updatedAt) {
		set("updated_at", updatedAt);
		return (M)this;
	}
	
	public java.lang.String getUpdatedAt() {
		return getStr("updated_at");
	}

	public M setLastLoginAt(java.lang.String lastLoginAt) {
		set("last_login_at", lastLoginAt);
		return (M)this;
	}
	
	public java.lang.String getLastLoginAt() {
		return getStr("last_login_at");
	}

	public M setEthAccount(java.lang.String ethAccount) {
		set("eth_account", ethAccount);
		return (M)this;
	}
	
	public java.lang.String getEthAccount() {
		return getStr("eth_account");
	}

}
