name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: bcaff64c017816974bec6e774c0b2f52b3fb1aee

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:

  kcoinprodch:
    orderers:

      - orderer-40819b875a240ee1c36fd4062361fba18476e82e-0.orderer-40819b875a240ee1c36fd4062361fba18476e82e.default.svc.cluster.local

    peers:

      peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      # - kcoinprod:1.0.0
      - ${fabricChainCodeId}

organizations:

  bcaff64c017816974bec6e774c0b2f52b3fb1aee:
    mspid: bcaff64c017816974bec6e774c0b2f52b3fb1aeeMSP

    cryptoPath:  ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/msp
    tlsCryptoKeyPath: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/tls/server.key
    tlsCryptoCertPath: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/tls/server.crt

    peers:

      - peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local

    certificateAuthorities:
      - ca-org1

    signedCert:
      path: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/msp/signcerts/User1@bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local-cert.pem

    adminPrivateKey:
      path: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/msp/keystore/${adminPrivateKeyFile}

  ordererorg:
      mspID: "40819b875a240ee1c36fd4062361fba18476e82eMSP"

      cryptoPath: ${fabricCertificatesPath}/40819b875a240ee1c36fd4062361fba18476e82e.orderer/msp
# orderer-eip: 49.4.7.166
orderers:

  orderer-40819b875a240ee1c36fd4062361fba18476e82e-0.orderer-40819b875a240ee1c36fd4062361fba18476e82e.default.svc.cluster.local:
    url: grpcs://orderer-40819b875a240ee1c36fd4062361fba18476e82e-0.orderer-40819b875a240ee1c36fd4062361fba18476e82e.default.svc.cluster.local:30805

    grpcOptions:
      ssl-target-name-override: orderer-40819b875a240ee1c36fd4062361fba18476e82e-0.orderer-40819b875a240ee1c36fd4062361fba18476e82e.default.svc.cluster.local
      grpc-max-send-message-length: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: orderer-40819b875a240ee1c36fd4062361fba18476e82e-0.orderer-40819b875a240ee1c36fd4062361fba18476e82e.default.svc.cluster.local

    tlsCACerts:
      path: ${fabricCertificatesPath}/40819b875a240ee1c36fd4062361fba18476e82e.orderer/msp/tlscacerts/tlsca.40819b875a240ee1c36fd4062361fba18476e82e-cert.pem

peers:


  peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local:

    url: grpcs://peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local:30605

    eventUrl: grpcs://peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local:30705

    grpcOptions:
      ssl-target-name-override: peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      clientKeyFile: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/tls/server.key
      clientCertFile: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/tls/server.crt
      hostnameOverride: peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee-0.peer-bcaff64c017816974bec6e774c0b2f52b3fb1aee.default.svc.cluster.local

    tlsCACerts:
      path: ${fabricCertificatesPath}/bcaff64c017816974bec6e774c0b2f52b3fb1aee.peer/msp/tlscacerts/tlsca.bcaff64c017816974bec6e774c0b2f52b3fb1aee-cert.pem

certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1