name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: 51809cd89ab98256de47e9908c70c588a8e4db01

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:

  channel:
    orderers:

      - orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-0.orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.default.svc.cluster.local

    peers:

      peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      # - kcoindev:1.0.0
      - ${fabricChainCodeId}

organizations:

  51809cd89ab98256de47e9908c70c588a8e4db01:
    mspid: 51809cd89ab98256de47e9908c70c588a8e4db01MSP

    cryptoPath:  ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/msp
    tlsCryptoKeyPath: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/tls/server.key
    tlsCryptoCertPath: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/tls/server.crt

    peers:

      - peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local

    certificateAuthorities:
      - ca-org1

    signedCert:
      path: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/msp/signcerts/User1@51809cd89ab98256de47e9908c70c588a8e4db01.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local-cert.pem

    adminPrivateKey:
      path: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/msp/keystore/${adminPrivateKeyFile}

  ordererorg:
      mspID: "81efaa2f8ec402ad2c8743d99c0609550d4ca2f0MSP"

      cryptoPath: ${fabricCertificatesPath}/81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.orderer/msp
# orderer-eip: 117.78.48.87
orderers:

  orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-0.orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.default.svc.cluster.local:
    url: grpcs://orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-0.orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.default.svc.cluster.local:30805

    grpcOptions:
      ssl-target-name-override: orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-0.orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.default.svc.cluster.local
      grpc-max-send-message-length: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-0.orderer-81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.default.svc.cluster.local

    tlsCACerts:
      path: ${fabricCertificatesPath}/81efaa2f8ec402ad2c8743d99c0609550d4ca2f0.orderer/msp/tlscacerts/tlsca.81efaa2f8ec402ad2c8743d99c0609550d4ca2f0-cert.pem

peers:


  peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local:

    url: grpcs://peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local:30605

    eventUrl: grpcs://peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local:30705

    grpcOptions:
      ssl-target-name-override: peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      clientKeyFile: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/tls/server.key
      clientCertFile: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/tls/server.crt
      hostnameOverride: peer-51809cd89ab98256de47e9908c70c588a8e4db01-0.peer-51809cd89ab98256de47e9908c70c588a8e4db01.default.svc.cluster.local

    tlsCACerts:
      path: ${fabricCertificatesPath}/51809cd89ab98256de47e9908c70c588a8e4db01.peer/msp/tlscacerts/tlsca.51809cd89ab98256de47e9908c70c588a8e4db01-cert.pem

certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1